import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/base/Navbar';
import Sidebar from '@/components/base/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'VS Code',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-vscode-background-primary`}>
        <Navbar />
        <div className='flex'>
          <Sidebar />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
